style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/loewensteinph/fthelper
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
  commit_groups:
    title_maps:
      feat: 1. Features
      perf: 2. Performance Improvements
      fix: 3. Bug Fixes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
